Fixed postinst

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -3,17 +3,19 @@
 set -e
 
 #VARS
-SWING_FILE_OPENJDK8="/etc/java-8-openjdk/swing.properties"
+ ="/etc/java-8-openjdk/swing.properties"
 SWING_FILE_LLIUREX="/usr/share/lliurex-java-panel/swing.properties"
 PACKAGE_NAME="lliurex-java-panel"
 
 case "$1" in
    configure)
-		if dpkg-divert --package ${PACKAGE_NAME} --add  --rename  --divert ${SWING_FILE_OPENJDK8}.diverted ${SWING_FILE_OPENJDK8} ; then
-   			ln -fs ${SWING_FILE_LLIUREX} ${SWING_FILE_OPENJDK8}
-   		else
-   			echo "Unable to divert file \"$SWING_FILE_OPENJDK8\"" >&2
-		fi
+		if [ -f SWING_FILE_OPENJDK8 ];then
+			if dpkg-divert --package ${PACKAGE_NAME} --add  --rename  --divert ${SWING_FILE_OPENJDK8}.diverted ${SWING_FILE_OPENJDK8} ; then
+				ln -fs ${SWING_FILE_LLIUREX} ${SWING_FILE_OPENJDK8}
+   			else
+   				echo "Unable to divert file \"$SWING_FILE_OPENJDK8\"" >&2
+			fi
+		fi	
    				
    ;;
 
